# Generated by Django 3.1.3 on 2020-11-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201105_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='Rut',
            new_name='rut',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
